[profile.default]
src = "."
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Compiler settings
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = false

# Testing settings
verbosity = 2
fuzz = { runs = 256 }

# Network settings
[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/YOUR_API_KEY"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/YOUR_API_KEY"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" } 